onebusaway-nyc-vehicle-tracking-webapp/src/main/java/org/onebusaway/nyc/vehicle_tracking/webapp/controllers/BlockDetailsController.java
/**
 * Copyright (c) 2011 Metropolitan Transportation Authority
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.onebusaway.nyc.vehicle_tracking.webapp.controllers;

import java.util.HashMap;
import java.util.Map;

import org.onebusaway.gtfs.model.AgencyAndId;
import org.onebusaway.nyc.transit_data_federation.services.nyc.DestinationSignCodeService;
import org.onebusaway.transit_data.model.blocks.BlockBean;
import org.onebusaway.transit_data.model.blocks.BlockConfigurationBean;
import org.onebusaway.transit_data.model.blocks.BlockTripBean;
import org.onebusaway.transit_data.model.trips.TripBean;
import org.onebusaway.transit_data_federation.services.AgencyAndIdLibrary;
import org.onebusaway.transit_data_federation.services.beans.BlockBeanService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

@Controller
public class BlockDetailsController {

  private BlockBeanService _blockBeanService;

  private DestinationSignCodeService _destinationSignCodeService;

  @Autowired
  public void setBlockBeanService(BlockBeanService blockBeanService) {
    _blockBeanService = blockBeanService;
  }

  @Autowired
  public void setDestinationSignCodeService(
      DestinationSignCodeService destinationSignCodeService) {
    _destinationSignCodeService = destinationSignCodeService;
  }

  @RequestMapping(value = "/block-details.do", method = RequestMethod.GET)
  public ModelAndView index(@RequestParam String blockId) {

    AgencyAndId id = AgencyAndIdLibrary.convertFromString(blockId);
    BlockBean block = _blockBeanService.getBlockForId(id);

    if (block == null)
      return new ModelAndView("block-details-notFound.jspx");
    
    Map<String,String> dscsByTripId = new HashMap<String, String>();
    for( BlockConfigurationBean blockConfig : block.getConfigurations() ) {
      for( BlockTripBean blockTrip : blockConfig.getTrips() ) {
        TripBean trip = blockTrip.getTrip();
        AgencyAndId tripId = AgencyAndIdLibrary.convertFromString(trip.getId());
        String dsc = _destinationSignCodeService.getDestinationSignCodeForTripId(tripId);
        if (dsc == null)
          dsc = "NA";
        dscsByTripId.put(trip.getId(),dsc);
      }
    }

    Map<String, Object> model = new HashMap<String, Object>();
    model.put("block", block);
    model.put("dscs", dscsByTripId);
    return new ModelAndView("block-details.jspx", model);
  }

}

onebusaway-nyc-vehicle-tracking-webapp/src/main/java/org/onebusaway/nyc/vehicle_tracking/webapp/controllers/DataDebugController.java
/**
 * Copyright (c) 2011 Metropolitan Transportation Authority
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.onebusaway.nyc.vehicle_tracking.webapp.controllers;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import org.onebusaway.gtfs.model.AgencyAndId;
import org.onebusaway.nyc.transit_data_federation.services.nyc.DestinationSignCodeService;
import org.onebusaway.nyc.transit_data_federation.services.nyc.RunService;
import org.onebusaway.transit_data_federation.model.ShapePoints;
import org.onebusaway.transit_data_federation.services.shapes.ShapePointService;
import org.onebusaway.transit_data_federation.services.transit_graph.TransitGraphDao;
import org.onebusaway.transit_data_federation.services.transit_graph.TripEntry;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

@Controller
public class DataDebugController {

  @Autowired
  private TransitGraphDao _graphDao;
  
  @Autowired
  private DestinationSignCodeService _dscService;

  @Autowired
  private RunService _runService;

  @Autowired
  private ShapePointService _shapePointService;

  @RequestMapping(value = "/data-debug.do", method = RequestMethod.GET)
  public ModelAndView index() {

    List<AgencyAndId> tripsWithNullDSC = new ArrayList<AgencyAndId>();
    List<AgencyAndId> tripsWithNullRunId = new ArrayList<AgencyAndId>();
    List<AgencyAndId> tripsWithNoShape = new ArrayList<AgencyAndId>();
       
    for(TripEntry tripEntry : _graphDao.getAllTrips()) {
      AgencyAndId tripId = tripEntry.getId();
      String dsc = _dscService.getDestinationSignCodeForTripId(tripId);
      if(dsc == null) {
    	  tripsWithNullDSC.add(tripId);
      }
      
      Set<String> runIds = _runService.getRunIdsForTrip(tripEntry);
      if(runIds == null || runIds.isEmpty() == true) {
    	  tripsWithNullRunId.add(tripId);
      }
      
      if(tripEntry.getShapeId() == null) {
    	  tripsWithNoShape.add(tripId);
      } else {      
    	  ShapePoints shapePoints = _shapePointService.getShapePointsForShapeId(tripEntry.getShapeId());
    	  if(shapePoints == null || shapePoints.isEmpty() == true) {
    		  tripsWithNoShape.add(tripId);
    	  }
      }
    }
    
    DebugModel model = new DebugModel();
    model.setTripsWithNullDSCs(tripsWithNullDSC);
    model.setTripsWithNullRunId(tripsWithNullRunId);
    model.setTripsWithNoShape(tripsWithNoShape);
    
    return new ModelAndView("data-debug.jspx", "data", model);
  }

  public class DebugModel {
	  
	  private List<AgencyAndId> tripsWithNullDSCs;

	  private List<AgencyAndId> tripsWithNullRunId;

	  private List<AgencyAndId> tripsWithNoShape;

	  public List<AgencyAndId> getTripsWithNullDSCs() {
		  return tripsWithNullDSCs;
	  }

	  public void setTripsWithNullDSCs(List<AgencyAndId> tripsWithNullDSCs) {
		  this.tripsWithNullDSCs = tripsWithNullDSCs;
	  }

	  public List<AgencyAndId> getTripsWithNullRunId() {
		  return tripsWithNullRunId;
	  }

	  public void setTripsWithNullRunId(List<AgencyAndId> tripsWithNullRunId) {
		  this.tripsWithNullRunId = tripsWithNullRunId;
	  }

	  public List<AgencyAndId> getTripsWithNoShape() {
		  return tripsWithNoShape;
	  }

	  public void setTripsWithNoShape(List<AgencyAndId> tripsWithNoShape) {
		  this.tripsWithNoShape = tripsWithNoShape;
	  }

  }
  
}

onebusaway-nyc-vehicle-tracking-webapp/src/main/java/org/onebusaway/nyc/vehicle_tracking/webapp/controllers/ReleaseController.java
/**
 * Copyright (c) 2011 Metropolitan Transportation Authority
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.onebusaway.nyc.vehicle_tracking.webapp.controllers;

import java.io.IOException;
import java.io.OutputStreamWriter;

import javax.servlet.http.HttpServletResponse;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.codehaus.jackson.map.ObjectMapper;
import org.onebusaway.nyc.util.git.GitRepositoryHelper;
import org.onebusaway.nyc.util.model.GitRepositoryState;
/**
 * Controller for git status. 
 *
 */
@Controller
public class ReleaseController {

	ObjectMapper _mapper = new ObjectMapper();
	private GitRepositoryState gitState = null;
	
  @RequestMapping(value="/release.do", method=RequestMethod.GET)
  public void gitDetailsInJSON(HttpServletResponse response) throws IOException {
	  if (gitState == null) {
		  gitState = new GitRepositoryHelper().getGitRepositoryState();
	  }
	  OutputStreamWriter writer = new OutputStreamWriter(response.getOutputStream());
	  _mapper.writeValue(writer, gitState);
  }

}

onebusaway-nyc-vehicle-tracking-webapp/src/main/java/org/onebusaway/nyc/vehicle_tracking/webapp/controllers/StatusController.java
/**
 * Copyright (c) 2011 Metropolitan Transportation Authority
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.onebusaway.nyc.vehicle_tracking.webapp.controllers;

import java.io.BufferedInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStreamWriter;
import java.net.URL;

import javax.servlet.http.HttpServletResponse;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;
import org.apache.commons.io.IOUtils;
import org.codehaus.jackson.map.ObjectMapper;
import org.onebusaway.nyc.util.git.GitRepositoryHelper;
import org.onebusaway.nyc.util.model.GitRepositoryState;
import org.onebusaway.nyc.vehicle_tracking.services.queue.InputTask;
import org.onebusaway.nyc.vehicle_tracking.services.queue.OutputQueueSenderService;
/**
 * Controller for git status. 
 *
 */
@Controller
public class StatusController {

	private static final String INSTANCE_ID_URL = "http://169.254.169.254/latest/meta-data/instance-id";
	private static final String INSTANCE_TYPE_URL = "http://169.254.169.254/latest/meta-data/instance-type";
	private static final String AMI_ID_URL = "http://169.254.169.254/latest/meta-data/ami-id";
	private static final String PUBLIC_HOSTNAME_URL = "http://169.254.169.254/latest/meta-data/public-hostname";
	private static final String INTERNAL_HOSTNAME_URL = "http://169.254.169.254/latest/meta-data/hostname";

	private ObjectMapper _mapper = new ObjectMapper();
	private GitRepositoryState gitState = null;
	
	@Autowired
	private OutputQueueSenderService queueSenderService;
	
	@Autowired
	private InputTask inputTask;
	
	
  @RequestMapping(value="/status.do", method=RequestMethod.GET)
  public ModelAndView index() {
	  return new ModelAndView("status.jspx", "sm", getStatus());
  }

 @RequestMapping(value="/status-json.do", method=RequestMethod.GET)
  public void json(HttpServletResponse response) throws IOException {
	  OutputStreamWriter writer = new OutputStreamWriter(response.getOutputStream());
	  _mapper.writeValue(writer, getStatus());
  }

  private StatusModel getStatus() {
	  if (gitState == null) {
		  gitState = new GitRepositoryHelper().getGitRepositoryState();
	  }
  	  StatusModel status = new StatusModel();
	  status.setOutputService(queueSenderService.getClass().getName());
	  status.setHostname(queueSenderService.getPrimaryHostname());
	  status.setPrimary(queueSenderService.getIsPrimaryInferenceInstance());
	  status.setListenerTask(inputTask.getClass().getName());
	  status.setDepotList(inputTask.getDepotPartitionKey());
	  status.setGitDescribe(gitState.getDescribe());
	  status.setInstanceId(slurp(INSTANCE_ID_URL));
	  status.setInstanceType(slurp(INSTANCE_TYPE_URL));
	  status.setAmiId(slurp(AMI_ID_URL));
	  status.setPublicHostname(slurp(PUBLIC_HOSTNAME_URL));
	  status.setInternalHostname(slurp(INTERNAL_HOSTNAME_URL));
	  return status;
  }
  
  private String slurp(String urlString) {
    URL url;
    InputStream is = null;
    BufferedInputStream bis = null;
    ByteArrayOutputStream baos = null;

    try {
      url = new URL(urlString);
      is = url.openStream();
      bis = new BufferedInputStream(is);
      baos = new ByteArrayOutputStream();
      IOUtils.copy(bis, baos);
    } catch (Exception any) {
      return any.toString();
    } finally {
      if (bis != null)
        try {
          bis.close();
        } catch (Exception e1) {
        }
      if (baos != null)
        try {
          baos.close();
        } catch (Exception e2) {
        }
    }
    return baos.toString();
  }
  
  public static class StatusModel {

	private String hostname;
    private boolean isPrimary;
	private String depotList;
	private String outputService;
	private String listenerTask;
	private String gitDescribe;
	private String instanceId;
	private String instanceType;
	private String amiId;
	private String publicHostname;
	private String internalHostname;

    public String getHostname() {
		return hostname;
	}
	public void setHostname(String hostname) {
		this.hostname = hostname;
	}
	public void setPrimary(boolean isPrimary) {
		this.isPrimary = isPrimary;
	}
	public boolean getPrimary() {
		return isPrimary;
	}
	public String getDepotList() {
		return depotList;
	}
	public void setDepotList(String depotList) {
		this.depotList = depotList;
	}
	public String getOutputService() {
		return outputService;
	}
	public void setOutputService(String outputService) {
		this.outputService = outputService;
	}
	public String getListenerTask() {
		return listenerTask;
	}
	public void setListenerTask(String listenerTask) {
		this.listenerTask = listenerTask;
	}
	public String getGitDescribe() {
		return gitDescribe;
	}
	public void setGitDescribe(String gitDescribe) {
		this.gitDescribe = gitDescribe;
	}
	public String getInstanceId() {
		return instanceId;
	}
	public void setInstanceId(String instanceId) {
		this.instanceId = instanceId;
	}
	public String getInstanceType() {
		return instanceType;
	}
	public void setInstanceType(String instanceType) {
		this.instanceType = instanceType;
	}
	public String getAmiId() {
		return amiId;
	}
	public void setAmiId(String amiId) {
		this.amiId = amiId;
	}
	public String getPublicHostname() {
		return publicHostname;
	}
	public void setPublicHostname(String publicHostname) {
		this.publicHostname = publicHostname;
	}
	public String getInternalHostname() {
		return internalHostname;
	}
	public void setInternalHostname(String internalHostname) {
		this.internalHostname = internalHostname;
	}

	
	public String toString() {
		return "Status:{"
				+ "listenerTask=" + this.listenerTask
				+ ", outputService=" + this.outputService
				+ ", hostname=" + this.hostname
				+ ", depotList=" + this.depotList + "}";
	}
  }
  

}

onebusaway-nyc-vehicle-tracking-webapp/src/main/webapp/WEB-INF/jsp/block-details.jspx
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2011 Metropolitan Transportation Authority

    Licensed under the Apache License, Version 2.0 (the "License"); you may not
    use this file except in compliance with the License. You may obtain a copy of
    the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
    License for the specific language governing permissions and limitations under
    the License.

-->
<html xmlns:jsp="http://java.sun.com/JSP/Page"
    xmlns:c="http://java.sun.com/jsp/jstl/core"
    xmlns:form="http://www.springframework.org/tags/form">
<jsp:directive.page contentType="text/html" />
<head>
<title>Block Details</title>
</head>
<body>

<h2>Block Details</h2>

<c:forEach var="blockConfig" items="${block.configurations}">
    <h3>Block Configuration</h3>
    <h4>ServiceIds - Active</h4>
    <ul>
        <c:forEach var="serviceId"
            items="${blockConfig.activeServiceIds}">
            <c:out value="${serviceId}" />
        </c:forEach>
    </ul>
    <h4>ServiceIds - Inactive</h4>
    <ul>
        <c:forEach var="serviceId"
            items="${blockConfig.inactiveServiceIds}">
            <c:out value="${serviceId}" />
        </c:forEach>
    </ul>
    <h4>Trips</h4>
    <table>
        <thead>
            <tr>
                <td>id</td>
                <td>route</td>
                <td>headsign</td>
                <td>dsc</td>
            </tr>
        </thead>
        <tbody>
            <c:forEach var="blockTrip" items="${blockConfig.trips}">
                <tr>
                    <c:set var="trip" value="${blockTrip.trip}" />
                    <td><c:out value="${trip.id}" /></td>
                    <td><c:out value="${trip.route.shortName}" /></td>
                    <td><c:out value="${trip.tripHeadsign}" /></td>
                    <td><c:out value="${dscs[trip.id]}" /></td>
                </tr>
            </c:forEach>
        </tbody>
    </table>
</c:forEach>

</body>
</html>

onebusaway-nyc-vehicle-tracking-webapp/src/main/webapp/WEB-INF/jsp/data-debug.jspx
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2011 Metropolitan Transportation Authority

    Licensed under the Apache License, Version 2.0 (the "License"); you may not
    use this file except in compliance with the License. You may obtain a copy of
    the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
    License for the specific language governing permissions and limitations under
    the License.

-->
<html xmlns:jsp="http://java.sun.com/JSP/Page"
    xmlns:c="http://java.sun.com/jsp/jstl/core"
    xmlns:form="http://www.springframework.org/tags/form">
<jsp:directive.page contentType="text/html" />
<head>
<title>Data Debug</title>
</head>
<body>

<h2>Trips with NULL DSCs</h2>

<ul>
  <c:forEach var="tripId" items="${data.tripsWithNullDSCs}">
  	<li><c:out value="${tripId}" /></li>
  </c:forEach>
</ul>

<h2>Trips with NULL Run ID</h2>

<ul>
  <c:forEach var="tripId" items="${data.tripsWithNullRunId}">
  	<li><c:out value="${tripId}" /></li>
  </c:forEach>
</ul>

<h2>Trips with No Shape</h2>

<ul>
  <c:forEach var="tripId" items="${data.tripsWithNoShape}">
  	<li><c:out value="${tripId}" /></li>
  </c:forEach>
</ul>

</body>
</html>

onebusaway-nyc-vehicle-tracking-webapp/src/main/webapp/WEB-INF/jsp/release.jspx
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2011 Metropolitan Transportation Authority

    Licensed under the Apache License, Version 2.0 (the "License"); you may not
    use this file except in compliance with the License. You may obtain a copy of
    the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
    License for the specific language governing permissions and limitations under
    the License.

-->
<html xmlns:jsp="http://java.sun.com/JSP/Page"
	xmlns:c="http://java.sun.com/jsp/jstl/core">
<jsp:directive.page contentType="text/html" />
<head>
</head>
<body>
<small><pre><c:out value="${git.details}" /></pre></small>
</body>
</html>

onebusaway-nyc-vehicle-tracking-webapp/src/main/webapp/WEB-INF/jsp/status.jspx
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2011 Metropolitan Transportation Authority

    Licensed under the Apache License, Version 2.0 (the "License"); you may not
    use this file except in compliance with the License. You may obtain a copy of
    the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
    License for the specific language governing permissions and limitations under
    the License.

-->
<html xmlns:jsp="http://java.sun.com/JSP/Page"
	xmlns:c="http://java.sun.com/jsp/jstl/core">
<jsp:directive.page contentType="text/html" />
<head>
<title>Status</title>
</head>
<body>
	<p>
		<b>ListenerTask:</b> <c:out value="${sm.listenerTask}" />
		<br/>
		<b>OutputService:</b> <c:out value="${sm.outputService}" />
		<br/>
		<b>HostName:</b> <c:out value="${sm.hostname}" />
		<br/>
		<b>Depots:</b> <c:out value="${sm.depotList}" />
		<br/>
		<b>IsPrimary?:</b> <c:out value="${sm.primary}" />
		<br/>
		<b>Git Version:</b> <c:out value="${sm.gitDescribe}" />
		<br/>
		<b>Instance Id:</b> <c:out value="${sm.instanceId}" />
		<br/>
		<b>Instance Type:</b> <c:out value="${sm.instanceType}" />
		<br/>
		<b>AMI Id:</b> <c:out value="${sm.amiId}" />
		<br/>
		<b>Public Hostname:</b> <c:out value="${sm.publicHostname}" />
		<br/>
		<b>Internal Hostname:</b> <c:out value="${sm.internalHostname}" />
		<br/>

	</p>
</body>
</html>

onebusaway-nyc-vehicle-tracking-webapp/src/main/webapp/WEB-INF/jsp/vehicle-location-bad-particles.jspx
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2011 Metropolitan Transportation Authority

    Licensed under the Apache License, Version 2.0 (the "License"); you may not
    use this file except in compliance with the License. You may obtain a copy of
    the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
    License for the specific language governing permissions and limitations under
    the License.

-->
<html xmlns:jsp="http://java.sun.com/JSP/Page"
    xmlns:c="http://java.sun.com/jsp/jstl/core"
    xmlns:fmt="http://java.sun.com/jsp/jstl/fmt"
    xmlns:form="http://www.springframework.org/tags/form">
<jsp:directive.page contentType="text/html" />
<head>
<title>Vehicle Location - Bad Particles</title>
</head>
<style>
table td {
   border: 1px solid black;
}
</style>
<body>

<h2>Bad Particles</h2>

<c:set var="particles" value="${particles}" scope="request" />

<jsp:include page="particles-snippet.jspx" />

</body>
</html>